name: vector_tile_renderer
description: A vector tile renderer for use in creating map tile images or writing to a canvas.
version: 7.0.0-beta.2
homepage: https://github.com/greensopinion/dart-vector-tile-renderer

environment:
  sdk: ">=3.6.0-0 <4.0.0"
  flutter: '>=3.37.0-0'

dependencies:
  flutter:
    sdk: flutter
  vector_tile: ^2.0.0
  fixnum: ^1.0.0
  collection: ^1.17.2
  flutter_gpu:
    sdk: flutter
  flutter_gpu_shaders: ^0.3.0
  native_assets_cli: ^0.13.0
  flutter_scene: ^0.9.2-0
  vector_math: ^2.1.4
  dart_earcut: ^1.2.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  flutter_lints: ^3.0.1
  test: ^1.17.5

flutter:
  assets:
    - build/shaderbundles/
