name: vector_tile_renderer
description: A vector tile renderer for use in creating map tile images or writing to a canvas.
version: 2.6.3
homepage: https://github.com/greensopinion/dart-vector-tile-renderer

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.14"

dependencies:
  flutter:
    sdk: flutter
  vector_tile: ^1.0.0
  fixnum: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  flutter_lints: ^2.0.1
  test: ^1.17.5
