name: vector_tile_renderer
description: A vector tile renderer for use in creating map tile images or writing to a canvas.
version: 2.4.3
homepage: https://github.com/greensopinion/dart-vector-tile-renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_tile: ^0.3.2
    #path: ../dart-vector-tile
  fixnum: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  flutter_lints: ^1.0.4
  test: ^1.17.5
