name: vector_tile_renderer
description: A vector tile renderer for use in creating map tile images or writing to a canvas.
version: 5.2.2
homepage: https://github.com/greensopinion/dart-vector-tile-renderer

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  vector_tile: ^2.0.0
  fixnum: ^1.0.0
  collection: ^1.17.2

dev_dependencies:
  benchmark_harness: ^2.0.0
  flutter_lints: ^3.0.1
  test: ^1.17.5
